In [1]:
import random
import pandas as pd
import numpy as np

In [2]:
def table(M,N):
    if M<50 and N<40:
        return np.random.randint(1,101,(M,N))
print(table(5,6))

[[60 59 22 53 37 51]
 [ 3 20 56 96 29  3]
 [16 75 31 79 39 65]
 [23 39 52 38 88 52]
 [26 21 43 98 34 20]]


In [3]:
table_a = table(5,6)
print(table_a)

[[23 35 47 70 17 93]
 [86 49 66 44 16 66]
 [29 82 21  3 16 68]
 [58 70 27 14 87 70]
 [21 31 60  7 80 50]]


In [4]:
print(table_a[2])

[29 82 21  3 16 68]


In [5]:
print(table_a[:,2])

[47 66 21 27 60]


In [6]:
table_a[-1] = 7
print(table_a)

[[23 35 47 70 17 93]
 [86 49 66 44 16 66]
 [29 82 21  3 16 68]
 [58 70 27 14 87 70]
 [ 7  7  7  7  7  7]]


In [7]:
table_a[:,-1] = table_a[:,0] + table_a[:,1]
print (table_a)


[[ 23  35  47  70  17  58]
 [ 86  49  66  44  16 135]
 [ 29  82  21   3  16 111]
 [ 58  70  27  14  87 128]
 [  7   7   7   7   7  14]]
